import web3 from './web3';

// Deployed contract's address
const address = '0x6C8722324660837F30F9570A92A474cEB514a26F';

// Deployed contract's interface
const abi = [{"constant":true,"inputs":[],"name":"totalIssuers","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"recipientAddress","type":"address"},{"name":"certificateId","type":"uint256"},{"name":"digitalSignature","type":"bytes"}],"name":"issueCertificate","outputs":[{"name":"issuedCertificateId","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"certificateId","type":"uint256"}],"name":"getCertificate","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"totalCertificates","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"name","type":"string"},{"name":"email","type":"string"},{"name":"description","type":"string"}],"name":"addIssuer","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"getIssuerCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getCertificateCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"issuerId","type":"uint256"}],"name":"getIssuer","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"totalIssuedCertificates","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"name","type":"string"},{"name":"description","type":"string"},{"name":"criteria","type":"string"}],"name":"addCertificate","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"issuingId","type":"uint256"},{"name":"calculatedHash","type":"bytes"}],"name":"verifyCertificate","outputs":[{"name":"validCertificate","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"}];

export default new web3.eth.Contract(abi, address);
